Update Image and website url
autogenhub/autogen pull request #14
Opened 2024-08-25 23:31 UTC by yiranwu0

## Why are these changes needed?

1. Update url of  cq-math and stateflow notebook, so that images can be shown in github repo.
  2. Change all `https://github.com/microsoft` to `https://github.com/autogen-ai`

## Related issue number

## Checks

- [ ] I've included any doc changes needed for https://autogen-ai.github.io/autogen/. See https://autogen-ai.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-08-25 23:58 UTC, marklysze approved these changes
Tested a few pages and looks good, thanks @yiranwu0

2024-08-26 14:21 UTC, sonichi requested changes
Could you please resolve the conflicts?

2024-08-26 14:21 UTC, sonichi commented on notebook/agentchat_RetrieveChat.ipynb
> +      "- `lgbm_spark`: The class for fine-tuning Spark version LightGBM models, using [SynapseML](https://autogen-ai.github.io/SynapseML/docs/features/lightgbm/about/) API.\n",
remove this change, and a few similar ones below.

2024-08-26 14:21 UTC, sonichi commented on notebook/agentchat_RetrieveChat_pgvector.ipynb
> +      "- `lgbm_spark`: The class for fine-tuning Spark version LightGBM models, using [SynapseML](https://autogen-ai.github.io/SynapseML/docs/features/lightgbm/about/) API.\n",
same

2024-08-26 14:21 UTC, sonichi commented on notebook/agentchat_RetrieveChat_qdrant.ipynb
> +      ":fire: Heads-up: We have migrated [AutoGen](https://autogen-ai.github.io/autogen/) into a dedicated [github repository](https://github.com/microsoft/autogen). Alongside this move, we have also
```suggestion
      ":fire: Heads-up: We have migrated [AutoGen](https://autogen-ai.github.io/autogen/) into a dedicated [github repository](https://github.com/autogen-ai/autogen). Alongside this move, we have also launched a dedicated [Discord](https://discord.gg/pAbnFJrkgZ) server and a [website](https://autogen-ai.github.io/autogen/) for comprehensive documentation.\n",
```

2024-08-26 14:21 UTC, sonichi commented on notebook/agentchat_RetrieveChat_qdrant.ipynb
> +      "FLAML is powered by a series of [research studies](https://autogen-ai.github.io/FLAML/docs/Research/) from Microsoft Research and collaborators such as Penn State University, Stevens Institute
For FLAML, this link is invalid and it's better to keep the original link for now. There are similar cases below.

2024-08-26 18:28 UTC, yiranwu0 commented
@Hk669 Can you take a look at this PR? I saw you made the same changes in PR #14 and already merged it

2024-08-26 18:36 UTC, Hk669 commented
> @Hk669 Can you take a look at this PR? I saw you made the same changes in PR #18 and already merged it

looks good to me. please merge it. thanks @yiranwu0

2024-08-26 18:36 UTC, Hk669 approved these changes

2024-08-26 21:14 UTC, sonichi approved these changes

2024-08-26 21:15 UTC, merged